### PR TITLE
Fix to the issue with FB login

### PR DESCRIPTION
**Pull request by ghost**
New pull request with elements only related to this issue

### CODE REVIEW

**Comment by babak-feiz** [comment]
PR was closed accidentally by ZenHub - not meant to be closed yet.

**Review by emiltin — COMMENTED** [review]
hi can you confirm that it's correct that this commit should affect 327 files? Is that because there's a bunch of new FB API files?

**Comment by babak-feiz** [comment]
Hi Emil

That is true. The majority of the file changes belong to the Facebook SDK (third-party library, aka "pod"). 

Usually you wouldn't add a third-party library to source control, but apparently the iOS pod framework (CocoaPods) doesn't always keep older pod versions. I encountered that issue when I was upgrading the code to match current IDE version. Others have had similar issues as well, apparently - see [here](https://www.dzombak.com/blog/2014/03/including-pods-in-source-control.html) for example. So the most secure option is to keep pods in source control.

**Comment by emiltin** [comment]
Hmm, that's an unfortunate practice I think, but we'll leave it for now. Merging.

**Pull request merged**
