### PR TITLE
Removed references to GA

### PR DESCRIPTION
**Pull request by ghost**
Also checked for all references to the removed keys

### CODE REVIEW

**Comment by emiltin** [comment]
fixes #35.
look good to go, why was this pr closed?

**Comment by babak-feiz** [comment]
When I created the PR, it created an extra item on ZenHub. I closed that item as it was unnecessary, apparently that also closed the PR. The PR was, nevertheless, not meant to be closed.

**Comment by emiltin** [comment]
ok will merge after facebook login fix

**Comment by babak-feiz** [comment]
Hi Emil

Now that the Facebook login PR is merged, can you merge this one as well, so we can proceed to TestFlight?

**Comment by emiltin** [comment]
merged

**Pull request merged**
